apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school-dev

resources:
- ../../base/admission
- ../../base/auth
- ../../base/notification
- ../../base/otp
- ingress.yaml

images:
- name: ghcr.io/cybe-asia/admission-services
  newName: ghcr.io/cybe-asia/admission-services
  newTag: dev-ab22ea3
- name: ghcr.io/cybe-asia/auth-services
  newName: ghcr.io/cybe-asia/auth-services
  newTag: dev-28eedfa
- name: ghcr.io/cybe-asia/notification-services
  newName: ghcr.io/cybe-asia/notification-services
  newTag: dev-488a8fd
- name: ghcr.io/cybe-asia/otp-services
  newName: ghcr.io/cybe-asia/otp-services
  newTag: dev-7af0499
