apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school-dev

resources:
- namespace.yaml
- ../../base/admission
- ../../base/auth
- ../../base/notification
- ../../base/otp
- ../../base/frontend
- ../../base/neo4j
- ../../base/governance
- ingress.yaml
- resource-quota.yaml
- app-config.yaml
- app-secrets-sealed.yaml
- neo4j-secret-sealed.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31080
  target:
    kind: Service
    name: admission-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31083
  target:
    kind: Service
    name: auth-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31082
  target:
    kind: Service
    name: notification-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31084
  target:
    kind: Service
    name: otp-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31085
  target:
    kind: Service
    name: frontend
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: API_GATEWAY_URL
        value: "http://traefik.kube-system.svc.cluster.local"
  target:
    kind: Deployment
    name: frontend

images:
- name: ghcr.io/cybe-asia/admission-services
  newName: ghcr.io/cybe-asia/admission-services
  newTag: sha-59278e2
- name: ghcr.io/cybe-asia/auth-services
  newName: ghcr.io/cybe-asia/auth-services
  newTag: sha-e8d1cbf
- name: ghcr.io/cybe-asia/digital-school-frontend
  newName: ghcr.io/cybe-asia/digital-school-frontend
  newTag: sha-08b660c
- name: ghcr.io/cybe-asia/notification-services
  newName: ghcr.io/cybe-asia/notification-services
  newTag: sha-6e55e14
- name: ghcr.io/cybe-asia/otp-services
  newName: ghcr.io/cybe-asia/otp-services
  newTag: sha-96632d7
