apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school-dev

resources:
- ../../base/admission
- ../../base/auth
- ../../base/notification
- ../../base/otp
- ../../base/frontend
- ingress.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31080
  target:
    kind: Service
    name: admission-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31083
  target:
    kind: Service
    name: auth-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31082
  target:
    kind: Service
    name: notification-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31084
  target:
    kind: Service
    name: otp-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31085
  target:
    kind: Service
    name: frontend

images:
- name: ghcr.io/cybe-asia/admission-services
  newName: ghcr.io/cybe-asia/admission-services
  newTag: dev-a4cc841
- name: ghcr.io/cybe-asia/auth-services
  newName: ghcr.io/cybe-asia/auth-services
  newTag: dev-79341be
- name: ghcr.io/cybe-asia/digital-school-frontend
  newName: ghcr.io/cybe-asia/digital-school-frontend
  newTag: dev-981da95
- name: ghcr.io/cybe-asia/notification-services
  newName: ghcr.io/cybe-asia/notification-services
  newTag: dev-a11e3e4
- name: ghcr.io/cybe-asia/otp-services
  newName: ghcr.io/cybe-asia/otp-services
  newTag: dev-6dea360
