apiVersion: batch/v1
kind: CronJob
metadata:
  name: moodle-cron
  namespace: moodle
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: moodle-cron
              image: ghcr.io/cybe-asia/digital-school-moodle:latest
              command:
                - php
                - /var/www/html/public/admin/cli/cron.php
          restartPolicy: OnFailure
