apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        kubernetes.io/hostname: cybe-dell-r250-01
      containers:
        - name: notification-service
          image: ghcr.io/cybe-asia/notification-services
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: NEO4J_URI
              value: "neo4j://neo4j.school-dev.svc.cluster.local:7687"
            - name: NEO4J_USER
              value: "neo4j"
            - name: NEO4J_PASSWORD
              value: "password123"
            - name: EMAIL_FROM
              value: "no-reply@school.com"
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              value: "your_email@gmail.com"
            - name: SMTP_PASSWORD
              value: "your_app_password"
