apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school-staging

resources:
- ../../base/admission
- ../../base/auth
- ../../base/notification
- ../../base/otp
- ../../base/frontend
- ../../base/neo4j
- ../../base/governance
- ingress.yaml
- resource-quota.yaml
- app-config.yaml
- app-secrets-sealed.yaml
- neo4j-secret-sealed.yaml
- smoke-test-job.yaml

replicas:
- name: admission-service
  count: 2
- name: auth-service
  count: 2
- name: notification-service
  count: 2
- name: otp-service
  count: 2
- name: frontend
  count: 2

patches:
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31090
  target:
    kind: Service
    name: admission-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31093
  target:
    kind: Service
    name: auth-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31092
  target:
    kind: Service
    name: notification-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31094
  target:
    kind: Service
    name: otp-service
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 31095
  target:
    kind: Service
    name: frontend
images:
- name: ghcr.io/cybe-asia/admission-services
  newName: ghcr.io/cybe-asia/admission-services
  newTag: dev-9ebf50f
- name: ghcr.io/cybe-asia/auth-services
  newName: ghcr.io/cybe-asia/auth-services
  newTag: dev-79341be
- name: ghcr.io/cybe-asia/digital-school-frontend
  newName: ghcr.io/cybe-asia/digital-school-frontend
  newTag: dev-09a3a9b
- name: ghcr.io/cybe-asia/notification-services
  newName: ghcr.io/cybe-asia/notification-services
  newTag: dev-a11e3e4
- name: ghcr.io/cybe-asia/otp-services
  newName: ghcr.io/cybe-asia/otp-services
  newTag: dev-e0cab3a
