apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school-production

resources:
- ../../base/admission
- ../../base/auth
- ../../base/notification
- ../../base/otp
- ../../base/frontend
- ingress.yaml

patches:
  - target:
      kind: Service
      name: admission-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31100
  - target:
      kind: Service
      name: auth-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31103
  - target:
      kind: Service
      name: notification-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31102
  - target:
      kind: Service
      name: otp-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31104
  - target:
      kind: Service
      name: frontend
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31105

images:
- name: ghcr.io/cybe-asia/admission-services
  newName: ghcr.io/cybe-asia/admission-services
  newTag: production-latest
- name: ghcr.io/cybe-asia/auth-services
  newName: ghcr.io/cybe-asia/auth-services
  newTag: production-latest
- name: ghcr.io/cybe-asia/notification-services
  newName: ghcr.io/cybe-asia/notification-services
  newTag: production-latest
- name: ghcr.io/cybe-asia/otp-services
  newName: ghcr.io/cybe-asia/otp-services
  newTag: production-latest
- name: ghcr.io/cybe-asia/digital-school-frontend
  newName: ghcr.io/cybe-asia/digital-school-frontend
  newTag: production-latest
