---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: school-prod-blue
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgASZfeVmkrBn/dr0loQwc8GA6+78xltjeGj4GBHLC6qtegTockKAkJ+6hcPf/nTMmSDOL0ANyDOv8n71z57IFAmBxoYPqgLs90RIWy+TYB/+A7zPvw85gL/H0X5Rv4481Y01NY8cftC6V6NFxHY/KgV9aT1iGM11IopQFc+w8zrX69dhjtysLPUJ1i+hyxXVxXsPnBBijfIVJrMfhK5AlDjO2TOuIPYVORnUNH8Ofh0o1Y4/2i15/jPMmmVB31O3bmJsK8MiKwLc0KoMFUbP8li7f893likDw2dseU2qkHdS4WaXZN3W6C1shImZVlIBCjDZJrjZxQ10NOjFw2DYHJjZ8QNh4N3tMymp/D50H91svcDdXB8kPDGOqkk+wqedx9X6xAXUVcvl46WpMvJK0Xg+Jdu2gsHVg5Fd4MASomgLEi2sT4S5UoMtjUTwKDXK3H549W5MygdhZv6m8q76lB/k2/u2rnb3Wn7t6aEgykhwE1mhyuSViZ6NElD1y9IQ0etCl5mRcD5uZCv2CLRy9zdYZpZ9ciq/uYxfazhO/gaQRxblMgIbLMfmAlm2b+KyXGyF25mflSLu63zaXZbWrZGixFo7UWmvKsgA2nf6rmvo8GDU1+bwWp/C9Vmi+0OXjpfJfulEGyvfONo5q6d2dIAPGkZb/LsYRzF7sq+hdUmpkUgUW1YbPJjaYlZNkGZgW9HdPZjRbAXzyuS9AM5JnZdP7hFjxP5Rg0=
    MINIO_ROOT_USER: AgCfD3tGXg71Z3rjk+BuDfQABJYK2TsHkNNTyGacSCHi0uxg0SZUzKJSl3k0nwYu9uJgoodriKPVmEW2Yq3M+DAlUSo9Pzf9MhAfDEvmdS8GBUd9cslQpAz32q0msIPDxiFbE5scSzVqTc/wBBu9RQIK/u3aZ3QNgUyE7sPr1oScosHh1IGFsym+UBsKxAf859YiLvXktkqzG/M4h63SCUnro8YEJJea4aXzvuLGb+HMLHI25uF94ZsxIQDtBPfqNHVXOOlI2lum/xs7hHnDG4vnleZVi+/3Y+vdqpt/zz5beV9+mjQ91u2hOJYRpKpStc5OW7N8WjuIssdbplESpbP3JxXBlehRsRCx+h2TY36GTMI/ZhoGdQuiLMBeHuOXKrcDPnt9+McAwRrJlJpUtib9rXsnjm1cLokqAaHYLDMSSVL7Uc2uc+MDDfqJ6sEKatXxlk/+FwJ3qvsbTM5JIB4Yrc9aoRnCO9nP7RWAfS4mMQwRf+zkryMKNWkyKJ1PxFVeEBfu+EGJrNN//LNFtygaRz+VMDwB68uONUEWzk4se32gsB7ma/P2HFCBIzuIydlNUtNQEe0t0JFlFbzI7cXCN1mVyrGUFiza5lx0X2V5BpaEZUk7jFq/bkQoIQoU/WCIi5lEtcFBtMrlLmrz03ciMhRz6L7svE6qydxMiTZ0fj8gI4UsPHICHuFjKZgjnkUHC6lMgGPW6UYytQh2bIcgCVUBesCSDg0=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: school-prod-blue
