---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo4j-secret
  namespace: school-prod-blue
spec:
  encryptedData:
    NEO4J_AUTH: AgCd0Lk+cxWo8XHDSrseulvzb6g3bi2YrFPlmwylUOxeWVUFFoljeedO+SqpiQL6AKPR5n8wm49sFmDvUnDsRGcd0kD043H1U6/WTTRX2jZ9DTSG8gVr4Fu7moiofiFm7/OYlYkSBMIHIJUgRaP3cu4RPdcqNwno8D8OwTGuUDK0TbUR+icBJFVrNRWTJHhkta1Lmn6eH8TZ502HnOWFZB11Mvxy68t8GyLX9jQT+alpdRcgXbD173zDDAAmcMbBJLAK4Jhblec01KWn/Z95QFmxPSPz53LpEhKfat/TUT3l9uJkIhBKdP2myfJFCOFNbLbec2l5Pap2pGuADUAL+JQJId2oIX8o2ePROfAknZkoCV29P8OkDbLp1ZxTpXTtYL2HAJReIAp33dlPiwnoXL9HNdxQKP56XdSClFoqn0O8m1LSfoQIvtX3imgRbSeC/09kXSENZAdqv5n64d2tVCG7lqWfC1bKJLCnYOAkGq4KmIMIzBkPrGoQ1PSgx2h6n+9x61dEQIEwBABKoYOh6WlegDiCFdNBzMAH6G6vYYJ6X0SmQWpsqapXfXJmxj7xzkgQIAaQ+qe1Wq3t8Yhl6KG9UUD2At71FgkeSjceup40dvSpiH+sFrrfh4Yc9mrvfD1u6KOdMf9N5Lipp0HQbso16siDy+acBK65EftY8wl2Zout+uc9hg4o8lPX7p9DLmQ6qaNhNpx3RmjmndYzKHkeIm4Ijf+rPPYL1Cu8mZg=
  template:
    metadata:
      name: neo4j-secret
      namespace: school-prod-blue
    type: Opaque
