---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: school-prod-green
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCZbfJKAkvO+yo8mnkOTBPjQc/2JpIxUoocr0tPBgcozLWp8J3umcIJQBYSUc1xvtEc68+m+zop0ZhtsppGFivYJk+6ZJJ80GRygGupB0G8b62K6K8K8kTCVsOGBvNWAj0mzrdmZDpSVPevC56isEHC2ZV86zaUDHy746QMIRbSoWPiXGUBwQy0hxiLyPWC1wMVzxJ8oankt+A/R0kpctCwGZwCY4jdhBKSXYjev6mRIdFzpuyDyX79atEFMKYp2y9/e2f5L2Ocy7k6rWn6AIGJwZZcEd/8cTRucq4eJgnvBmzNm5SZnStqCzTcP4pN3MBXERE34POkysQkVLKO+NkQemb/kcImkHGmerjI9Zx/puGNxJZBUmJBCAdyJp5Cv3Gq/apCEY4ssUjybjon0hob8QIJtQH9VnpBApRoAy0ioAvQGVV0GsPFBR21u1aya2Z/7+i22W5NipDRvjAxIaWN75AHB+0zlqHd8RD0c2ePmLmBdNiUpP6FM+2t06VgKCpUk6/jsN2He+IrvSQ02NyQJaoEmh2JCeJ43yD26LAHv0ADwcBPVGK7C8Al+RRmE71xZ2NCtAduCF0yZ3sPdeeLm9E4TN3k9qnViWComx1jmDkZV2YeC1xpFgFnok+v0nUcG+WB/H4jjsoivTs0ai/dNdT9jou/3NJI/CwBncCDukyuQlQJecmgfF3LI3hvs+jXOxrExcQ88H7sGZ0YnCOCcg7RAFR2CCc=
    MINIO_ROOT_USER: AgANJ1am5JqjcMOJYj6aZyskZQfMOTy/W4umxRyHh7b1ELaPUi0q/AECfiQ/27488Qi+B1xPIZ9/KN95EksVVgVr8a6i6B9OW/6GVXPhvIKAuXsZ01yV/IYi7euIWcMv/+sqXqV8Z4FoqNN38E7GoKN6ipaA22OP4a70Q9JNjxFOVORT/jnzDaa/ZVmaKJZDEzevKfpOBvFbU14PaVQ68JCna32zFbMPotQS53JyJq3V7lJ2jaBvZtyxD0mo+rVBTN7rLtcYkaFBuT2KLX7HQoCA5K5r/wLnNluEczBkxCJQH2wff0PJJsNnd3A0fX9aP+863WG334UwK4FFDODWl3dPPE8v+wJTPAk6GZEosDUvEsOEAXPa3Ot3INXEEvXmEF57dozH3mMHOX9MlfHpOtLvnk2Dnqm5ygnHG1muJljdp3tlWfuKz2S+mFV/PwavwlrLc7/LfmHJopSCkG4IylRk0VwxJzGklAy8fp1NBSROBw3XyDxToMGn7YAClBfPptvUZcejROr/yO9GBSI3cZR4ZfB85IzW8QNDall05RxPKHfClXFNPv+2q3cqkNkJQrYyuWRrhTWPRaWk/mw/vJxGks0VBfgsBCCsL/OvTs5dyw2DX45TLHRVnlu5n8HR2W7ierC9VWN1uWtQnVsgTS+dtjVMn9mSwzJzDCX3gGXAygWLJPTqqjxy4ay0SHU9eLXb0dxlwA1f4CLVHyOljas1Memai42Sd8WC
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: school-prod-green
