---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo4j-secret
  namespace: school-prod-green
spec:
  encryptedData:
    NEO4J_AUTH: AgAVjSLeKA9Eq5dLleImCpeuYYR8jFm14iF+GPp0VZmZBFFjVXGTJL1ys9zbVjfjL50GgzKUjdtyJeJN7Jj3v/0znxItGBQcODoqvEndVYJkl6Rls79AjE51qY9bMw2ivLtpv171/S4D04eDDZriDYLTT0Ohq535cvFrQt+gXaZe+gl7bkv767BCwQ4o58n1aT0mVBduQZXSyNuGYSsfuphC6zIjfuA7qKl+lg5UdIccVCHRe8b/x2Dp2jiOTicZN7D/t+P8ZYYcfu/v/C/Z34a8f2cnv/l6qGw2rermq99g2XJzl/k14R0Mu4UlI2zqoyTE4Af3rumN54X/iYpC7Hoz8EJb6GSAiR8Of8NrismW8+R1XzyeCzHUx1y3nYHCNTMM8vqcU0XI05AIpK3awEo0Zemrd8WQCU4N0iJ08UzgnKCblkGAQ0+P2TvFZeRoXo6+P1RV9cKEkU5SA7KX3ES9qqtLCKHmlbtj13VLUuDl+dlpyuM2IL79whi6TPGr+nvFPqWE7ri4M30LivrYqAEKz9qtlRDkAGCwPAyR2t8BTRSOq5hzOE5599xc2ZsOkXZRUx5/+EBUYZoQn2G/j/dXqCiVyY+O1zhQjxUNViPKRrsXNd2G7C40AnhW0gFUKcCpCuKBSW051OmH2/bBsZ7+ylV4689xhGBCskRxgcYrI3bJKq+xLLo5+BU7ca1J7s5i/vR4f0MKy1yJmW4HGrP2u0NoTOkraF1Olv0Tra4=
  template:
    metadata:
      name: neo4j-secret
      namespace: school-prod-green
    type: Opaque
