apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: payment-service
          image: ghcr.io/ariefnugrahaaa/payment-services
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
