apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unleash

resources:
  - namespace.yaml
  - postgres.yaml
  - unleash-server.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - unleash-postgres-credentials.sealed.yaml
  - unleash-admin-credentials.sealed.yaml
