---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unleash-admin-credentials
  namespace: unleash
spec:
  encryptedData:
    adminPassword: AgCJa+WYeHHRHjEcjOIgTphJTkAXuvHirUdnvCZkCr6cc1X/dsKZHgbONRrKAp84ERDQvvv/lEzH2yRbWOhb+QzbJ6rx5AJYDgewtAFNZ7NV+U5gmuSw6p5oEzQd7enaQGxrIOwr+AQX58NmP5h3FGe+f5AqhfwdFfIPmBFJbaudS/CrdSzKqqqgYv8RnTaSrsGJLG4irOggSVKGoKcuyxnKfCBT0BdX9lw6rpsCuNHsbJwItUE9/qQTQ9iDCHKz1v4BkTgBMgGY0ClMy6RNUP91nCXnrkYuBBSJVEUNoVvvhwzoDE1tzmbgYK89I6bNMiycXsIb8iBQ+fWT19iXEtrnnOPzx+3dj+CrPa2dvwk/t/TtkMEY9UBWGx0Ib5dnofAyfU8scdzPrinXSlacegogRpHH0IbeD9n8olj7asI00bFzzu81ODmykhxUDcV5mqwPr4c3brCkaLzVRdgG2qGCxVQ3GwqzYziioNUNFygq+YTBN7gHniGw8+wkHTJlMdLMJhV5KsU94nfqMHyRjkYYvbfbyV627precuE0cGSi0VjfF7HWhYDLwfZHkD7ggDR3dSCmXfz9f0F55tz9aEe5AnHkqslfrVb4YwMN5lI2n6opgqaKuwxV/x3QaR8gJAOVQMeQY+2Ah5isggXZwojezHqPYt8pqmeaY6eEbvUfrkco1+6l6vJcK8kOZeFPYmVJLLCwJRvUXntNr/eFsl+13o3StuRRrKc=
    adminToken: AgBYXuE15N/tOuD+5FSlGr49Dg8vciifDGCC8DCY1D6pthUVE7XUO5vGI1UaPBuYLIYqzGWG0VatC6rxt1BgPTztKSLaD/2254TqdTm5IbiApXvgCD9FOouegXy46ffGhEqqOqMxokGZeXT/9e9Hai+ZyYw3WySuRMEg43lXDu2rh9w2jyK8nPMoodLN0DCFu0bxpKWDRStIoVMBOYf9waGSkDnCQs/v5FN8H8OkLJrJUO4M+JUyZ1e8dvnPbu5RN0tWcng8rjO8r9A2KPy7UOJlWkl6KguEGZOc+KvpXvhrnidRR+AnhSZ+b5oU5UR83tlkqN82B3Y16V2DsNNRgdMT04/jMNhLMQiu8KhY2MEqmIHkf8ZMsdmhpL2q319QgiNqLGiGdtG5o6FJD7QqaLn+NKR1M6ccKyH50oceZ/bci7Nn1ZcsTZoVcFxNm5pXf4nU6A+MAVgZ44gZHtVNQTfycw31bsNG3LSEEG0P1ixyWYrHIRrQXZqOC59ZFzSmwNDyvfVmEqHrFnQVLq5FxZTuPYqWqFBJowwtzf2JrzszIndcJ1U0vYjvyFPsaXjOkr6bjp2ZAMLifRh+PD2UI0xRO4yugXV3B7Uel++THF/9TBe9pb4XEXvrjLK+OP8jlWOYu3giOfGeQd2yk/zdJyWhu2uIyV/e8V85gNTx3uipE6Xh7yddMkwdZ+8lHoEG7FkVjnwoJsXxdwNY4zuWD0hfESeNd9V8BrRVuf+/FGo7PVfXhiLI8ce+lMX/J/kDNB2dDFQWFikSdCOZGgdvJiCETkkK+Q==
  template:
    metadata:
      creationTimestamp: null
      name: unleash-admin-credentials
      namespace: unleash
