---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret-sis
  namespace: school-staging
spec:
  encryptedData:
    .dockerconfigjson: AgB9sHbFzTTwX9/9yErIilRh921aW5o3j/sQLuTAOjJl+4pp/Yn0/d3UzPHv5UxxCTGhV/kFS7cqWs7AlHHP1KtxDtfbch0PSHR34UKKAyQXGdVTi2A44ENrOohoVSmrzg94OOgrmLEgRKqHiyrWj7X102CRpId9AEoTK/hmO8aOd8esPtbhP8m+5c8PHyfdLw6ky1B4PgR/CMJjgmgstwLGX7uJnZfp4o99Vzar6i7gOnjlmcjN/2zuyaGaaUx/cYzCfx/SBXLdIuQ5MN5d0mMecn06rbfPs+22smJkN9QArambacZYCkA6x+qyEyrsGuaobN+pJvl1Ui6L417BRvt+O8v1WMZU4tIm9PArGATuI5LN4guc8N9kQ1QywYfRB8+ywq5F0ilT+UNziykRqGLxP2gbamb8GjoGaYJW325u3PJA87Ce+wPQPgwXmGwtv1EBkiLl4VGw5noDAUdi3pRtRMNRXzmE94tjZxNu4IFxhF0HQ9C44EhOD9T9ASUfhtgmOIlbtOhvudzkczmLR+WK5q8NQTSFeUvu9EJrHbJRKfgNHRQ2chSmJB2huMfNz0IYx/3LyTuu9936w6mBlcgBBXpO1wgA1PH42/lSLGAygb9V75uEfl3eR8a9dPhQWgTfBr5nYq111WGnFj6iTGo5mNLQNgMDJJcM3j958I3rpX9t0pHbVQsxWmSOpd6LppVceZ7jEEtcLnmhBHkJHegZKWqSg03mR36pLvXb9rrmB/C/7re/kp7f804tUCIQDLIxqfClGxJb8JNdCCesVI2nUXAILsTJBpQrNoVyTpcHdYRlxhG1J1TX7+wHoASzKApdQUK/i5gG4dJAYc+Fluyo3blPFDNho4c3Lpp0XWYGSIcBy+MAiQuG+Q3j4qxJxFgmmsEHpGrz8OGfIVCsgXmkDdAr6FjAK/2aq+YYiQ5yLsQhnvS060MZRZXPBkKikw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret-sis
      namespace: school-staging
    type: kubernetes.io/dockerconfigjson
