---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAQp4EEuOHO7G3kPK+YMB7vmQDYQh4dl0NLP7zJDbTiIsE0MJdQ3q50zvua50CwtjT+vG5lEPxVENiIMToe6S6ckXIpkkS6VqPUj8th4NNtOv+mR/oTzpKQmG9/fT0f6flwWQTdmHyvn3/Xefi2curXA/JD2C9lw1YXPNX/gmsbALZra/nv63OtBFSZ3Uzey3r8E88CXf8i4UYpRbH/gEq6UTd0nw7OGrthY5IdAlYDeE2uD8hd3k5z0ZVUMLdWyzdS8vLNr9lWSRCvOqk2twV4yjCxkxZeWw8xRwFVziPl21spMfoNutHVpG52Gn93Udack+vVqrwY+Z7FiglsHNMHCMqfaCzHLW8BHDY0ffTvg2AF1TOAFP6Y9yPSh8vL2aa6vnCfk/S546e9a8TGr2tlJPfhC0Z1bWTvEToH2vq4QZbyZVHHbS7d2/QvPvtiRx+woba6AQJ2MOlIFUSEeohA+rtbF67vZyPVMbkOwJNDyb2zy6dD5UrqO2isLjV9gIeyvXBGa6RhmOaMKUe0Cd9cBTTCwa8e63k+kz0zw7ulBwf7KlmKzwp4Tti3Q9IKXQfM8UxBt35v4mAqwI4PGhNJkbZtfNkUAjYPho3bk+7VNYUrYDKLt89wuei7Bg3yxSNT0pfgbRSldD9KSuGM7HuLg1jvWkQyOlLOrPDO6Qbv8T3Rczcwg7rjI+/Zfkevbs87Vhls4JWMGtan0qn6tuo/8D8iYJZKLRk=
    admin-user: AgDAABX6k1+/+J33ukMOjn38n4Rp2pYfC4i8PG8NF/pUQ5FTlvWXlPWWDF/LYhii1pzt+U+ajyWpy2AmDtox+4na89YYpl5KyaHJQVC07UVp+QAfhEuxR2gCFveD3o7AZnhbYNIg68GZGncynXrBOLHTMiQ6XKKUcWzCKZ4n4Fc1XOW0Gl3qLpuHwLz7HSYxSE9FzZiLT455tJ/4wxa4lXgRGZAdwlptAic/5fsmp+yuEEXDjpvResPPEDRxGkyOESrfIyB3Rdj+0lxarqRy7wUAcuXd+viOqdEHx5VqX3boiWzMk0rNb2BtslsvePjaYCi0ocnxnBwevDpnKV2rAv10N6Tx5j0lSfw50uoirGTM69p+MIh+xTaPw6QNmfAfi+HpEpqdw+F+YS0NQvTQm19bt35CJldhjenMlRGwAp6VeLAXacBfdWWi1zA0eJ5rdzYs/0rl+EksLA5WBgZmDpSmsWvOQIDgPt/dwRnJPgI2RqpJkNQUT19PHn5IuNX5t2/PjJ15QeO48XdZv6M7RloD++fRXtOA5Vg7ZM4MknQxFz196mLAZGQ2zRjZBkuKUFNcQCHrISdCnvITjimmaARV6xFCkTCNkah4rVY89eEtaPLs/4oJ7J5aIC9QgtdOpYjKN5vZh3MKJUjL+uawnMrYADSOER/Iy5vnEDiweYtRUZVAzN357j441OKIjLUzr/+c8avqDg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
