# GHCR pull secret — copied from skillz-prod-blue.
# To refresh, run:
#   kubectl get secret ghcr-secret -n skillz-dev -o yaml | \
#     sed 's/namespace: skillz-dev/namespace: skillz-test/' | \
#     kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: skillz-test
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZmF1emktYWd1c3RpYW4iLCJwYXNzd29yZCI6ImdocF9xYk90bDlldVVUdUwyY3VFZGJVQW9VcnVQZjFyZHowV25FUVgiLCJhdXRoIjoiWm1GMWVta3RZV2QxYzNScFlXNDZaMmh3WDNGaVQzUnNPV1YxVlZSMVRESmpkVVZrWWxWQmIxVnlkVkJtTVhKa2VqQlhia1ZSV0E9PSJ9fX0=
