apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: skillz-test
stringData:
  MYSQL_DATABASE: moodle
  MYSQL_PASSWORD: moodlepassword
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: moodle
type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: skillz-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: skillz-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: mariadb-secret
        image: mariadb:10.11
        name: mariadb
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-storage
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: skillz-test
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mariadb
