apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otp-service
  template:
    metadata:
      labels:
        app: otp-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: otp-service
          image: ghcr.io/cybe-asia/otp-services
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
