apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-service
  template:
    metadata:
      labels:
        app: admission-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: admission-service
          image: ghcr.io/cybe-asia/admission-services
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
